---
driver:
  name: hyperv
  parent_vhd_folder: 'D:\Images'
  parent_vhd_name: 'WS2012R2-89.vhdx'
  memory_startup_bytes: 2GB
  vm_generation: 2

provisioner:
  name: chef_zero

transport:
  name: winrm
  elevated: true
  password: vagrant
  username: Vagrant

platforms:
  - name: windows-2012r2
suites:
  - name: packages
    run_list:
    - recipe[expand_disk]
    attributes:
      expand_disk:
        operations:
          disk0:
            partition2: '1GB'
